<?php

namespace Tests\Unit;

use App\Unit\CacheUtil;
use Doctrine\Common\Cache\FilesystemCache;
use PHPUnit\Framework\TestCase;

class CacheUnitTest extends TestCase
{
    /**
     * @var CacheUtil
     */
    private $cache;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->cache = new CacheUtil(new FilesystemCache(__DIR__.'/../../vars/cache'));
    }

    public function testSet(): void
    {
        $this->cache->set('key', 'OK',10);
        $this->assertEquals('OK', $this->cache->get('key'));
    }

    public function testGet(): void
    {
        $this->cache->set('key', 'OK');
        $this->assertEquals('OK', $this->cache->get('key'));
    }

    public function testHas(): void
    {
        $this->cache->set('key', 'OK');
        $this->assertTrue($this->cache->has('key'));
        $this->cache->delete('key');
        $this->assertFalse($this->cache->has('key'));
    }

    public function testDelete(): void
    {
        $this->cache->set('key', 'OK');
        $this->assertTrue($this->cache->has('key'));
        $this->cache->delete('key');
        $this->assertFalse($this->cache->has('key'));
    }
}
